name: "Checks and tests after build"
description: "Run the checks and tests once the wheels are built"
inputs:
  python-command:
    default: python3
    description: "Python command to use"
runs:
  using: "composite"
  steps:
    - name: Run basic pypowsybl import
      working-directory: ./tests
      shell: bash
      run: ${{ inputs.python-command }} basic_import_test.py

    - name: Run tests
      working-directory: ./tests # Run in subdir to use installed lib, not sources
      shell: bash
      run: ${{ inputs.python-command }} -m pytest

    - name: Type checking
      shell: bash
      run: mypy -p pypowsybl

    - name: Run doc examples
      working-directory: ./docs
      shell: bash
      run: make html doctest SPHINXOPTS="-W"

    - name: Test standalone cpp build
      shell: bash
      working-directory: ./dist
      run: | #Unzip binaries.zip produced by setup.py and try to build only the cpp API and bindings with it
        unzip binaries.zip && mkdir build && cd build
        cmake $GITHUB_WORKSPACE/cpp  -DBUILD_PYPOWSYBL_JAVA=OFF -DPYPOWSYBL_JAVA_LIBRARY_DIR=$GITHUB_WORKSPACE/dist/lib -DPYPOWSYBL_JAVA_INCLUDE_DIR=$GITHUB_WORKSPACE/dist/include
        cmake --build . --config Release
