name: Dev CI

on:
  pull_request:

permissions: { }

jobs:
  build:
    name: Build ${{ matrix.config.name }} wheel
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: linux,
            os: ubuntu-latest,
            container: "quay.io/pypa/manylinux_2_28_x86_64:2026.03.09-1",
            wheel-dir: "wheelhouse",
          }
          - {
            name: windows,
            os: windows-2022,
            wheel-dir: "dist",
          }
        python:
          - {
            name: cp312,
            abi: cp312,
            version: '3.12',
          }
    env:
      PYTHON: ${{ matrix.config.name == 'linux' && format('/opt/python/{0}-{1}/bin/python', matrix.python.name, matrix.python.abi) || 'python' }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Install Linux Packages
        if: matrix.config.name == 'linux'
        shell: bash
        run: dnf install -y wget

      - name: Setup environment
        uses: ./.github/actions/setup-before-build
        with:
          cache-prefix: ${{ matrix.config.name }}
          python-already-available: ${{ matrix.config.name == 'linux' && 'true' || 'false' }}
          python-version: ${{ matrix.python.version }}
          python-command: ${{ env.PYTHON }}

      - name: Checkout core sources
        uses: actions/checkout@v4
        with:
          repository: powsybl/powsybl-core
          ref: powerfactory_import_transformer_voltage_control
          path: powsybl-core

      - name: Build and install core
        shell: bash
        run: ./powsybl-core/mvnw --batch-mode -DskipTests=true --file powsybl-core/pom.xml install

      - name: Checkout olf sources
        uses: actions/checkout@v4
        with:
          repository: powsybl/powsybl-open-loadflow
          ref: transfo_continuous_control
          path: powsybl-open-loadflow

      - name: Build and install olf
        shell: bash
        run: ./powsybl-open-loadflow/mvnw --batch-mode -DskipTests=true --file powsybl-open-loadflow/pom.xml install

      - name: Setup path
        if: matrix.config.name == 'linux'
        run: echo "/opt/python/${{ matrix.python.name }}-${{ matrix.python.abi }}/bin/" >> $GITHUB_PATH

      - name: Build wheel
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.config.macosx_deployment_target }}
        run: |
          ${{ env.PYTHON }} setup.py bdist_wheel ${{ matrix.config.bdist_wheel_args }}
          if [ "${{ matrix.config.name }}" == "linux" ]; then
            auditwheel repair dist/*.whl
          fi

      - name: Install wheel
        run: ${{ env.PYTHON }} -m pip install ${{ matrix.config.wheel-dir }}/*.whl --user

      - name: Run basic pypowsybl import
        working-directory: ./tests
        run: ${{ env.PYTHON }} basic_import_test.py

      - name: Run tests
        working-directory: ./tests # Run in subdir to use installed lib, not sources
        run: ${{ env.PYTHON }} -m pytest

      - name: Type checking
        run: mypy -p pypowsybl

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: pypowsybl-wheel-${{ matrix.config.name }}-${{ matrix.python.name }}
          path: dist/*.whl
