name: Dev CI

on:
  pull_request:

permissions: { }

jobs:
  build:
    name: Build ${{ matrix.config.name }} wheel
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: linux,
            os: ubuntu-latest,
            container: "quay.io/pypa/manylinux_2_28_x86_64:2026.03.09-1",
            wheel-dir: "wheelhouse",
          }
          - {
            name: darwin,
            os: macos-15-intel,
            macosx_deployment_target: "10.16", # to ensure pip finds wheel when Big Sur is configured to return 10.16 as version instead of 11.0
            bdist_wheel_args: "--plat-name macosx-11.0-x86_64", # needed to avoid the wheel to be named -universal2
            wheel-dir: "dist",
          }
          - {
            name: windows,
            os: windows-2022,
            wheel-dir: "dist",
          }
        python:
          - {
            name: cp310,
            abi: cp310,
            version: '3.10',
          }
    env:
      PYTHON: ${{ matrix.config.name == 'linux' && format('/opt/python/{0}-{1}/bin/python', matrix.python.name, matrix.python.abi) || 'python' }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Install Linux Packages
        if: matrix.config.name == 'linux'
        run: dnf install -y wget

      - name: Setup path
        if: matrix.config.name == 'linux'
        run: echo "/opt/python/${{ matrix.python.name }}-${{ matrix.python.abi }}/bin/" >> $GITHUB_PATH

      - name: Setup environment
        uses: ./.github/actions/setup-before-build
        with:
          cache-prefix: ${{ matrix.config.name }}
          python-already-available: ${{ matrix.config.name == 'linux' && 'true' || 'false' }}
          python-version: ${{ matrix.python.version }}
          python-command: ${{ env.PYTHON }}

      - name: Build wheel
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.config.macosx_deployment_target }}
        run: |
          ${{ env.PYTHON }} setup.py bdist_wheel ${{ matrix.config.bdist_wheel_args }}
          if [ "${{ matrix.config.name }}" == "linux" ]; then
            auditwheel repair dist/*.whl
          fi

      - name: Install wheel
        run: ${{ env.PYTHON }} -m pip install ${{ matrix.config.wheel-dir }}/*.whl --user

      - name: Checks and tests
        uses: ./.github/actions/checks-after-build
        with:
          python-command: ${{ env.PYTHON }}

  sonar_python:
    name: Run SonarCloud analysis for Python code (${{ matrix.config.name }})
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ${{ matrix.config.os }}
    permissions:
      contents: read
      pull-requests: read
    container: quay.io/pypa/manylinux_2_28_x86_64:2026.03.09-1
    strategy:
      matrix:
        config:
          - {
            name: linux,
            os: ubuntu-latest,
          }
        python:
          - {
            name: cp310,
            abi: cp310,
            version: '3.10',
          }

    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Linux Packages
        run: dnf install -y wget

      - name: Setup path
        run: echo "/opt/python/${{ matrix.python.name }}-${{ matrix.python.abi }}/bin/" >> $GITHUB_PATH

      - name: Setup environment
        uses: ./.github/actions/setup-before-build
        with:
          cache-prefix: ${{ matrix.config.name }}

      - name: Install the package
        run: |
          pip install -e .

      - name: Generate coverage
        run: |
          coverage run -m pytest tests/
          coverage xml

      - name: Linting
        run: pylint pypowsybl

      - name: Sonar analysis
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.python.coverage.reportPaths=coverage.xml

  sonar_java:
    name: Run SonarCloud analysis for Java code (linux)
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven (Ubuntu)
        working-directory: ./java
        run: >
          ./mvnw -B -ntp -Pjacoco install

      - name: Run SonarCloud analysis
        working-directory: ./java
        run: >
          ./mvnw -B -ntp -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=powsybl_pypowsybl-java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
