name: Dev CI

on:
  pull_request:

permissions: { }

jobs:
  macos_windows_build:
    name: Build ${{ matrix.config.name }} ${{ matrix.python.name }} wheel
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: windows,
            os: windows-2022,
          }
        python:
          - {
            name: cp312,
            version: '3.12',
          }

    steps:
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout core sources
        uses: actions/checkout@v4
        with:
          repository: powsybl/powsybl-core
          ref: pf_integration_gj
          path: powsybl-core

      - name: Build and install core
        shell: bash
        run: mvn --batch-mode -DskipTests=true --file powsybl-core/pom.xml install

      - name: Checkout olf sources
        uses: actions/checkout@v4
        with:
          repository: powsybl/powsybl-open-loadflow
          ref: transfo_continuous_control
          path: powsybl-open-loadflow

      - name: Build and install olf
        shell: bash
        run: mvn --batch-mode -DskipTests=true --file powsybl-open-loadflow/pom.xml install

      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Linux Packages
        run: dnf install -y wget

      - name: Setup path
        run: echo "/opt/python/${{ env.PYTHON_VERSION }}-${{ env.PYTHON_VERSION }}/bin/" >> $GITHUB_PATH

      - name: Setup environment
        uses: ./.github/actions/setup-before-build
        with:
          cache-prefix: "linux"

      - name: Install the package
        run: |
          pip install -e .

      - name: Generate coverage
        run: |
          coverage run -m pytest tests/
          coverage xml

      - name: Linting
        run: pylint pypowsybl

      - name: Sonar analysis
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Run doc examples
        working-directory: ./docs
        run: make html doctest SPHINXOPTS="-W"

      - name: Test standalone cpp build
        shell: bash
        working-directory: ./dist
        run: | #Unzip binaries.zip produced by setup.py and try to build only the cpp API and bindings with it
          unzip binaries.zip && mkdir build && cd build
          cmake $GITHUB_WORKSPACE/cpp  -DBUILD_PYPOWSYBL_JAVA=OFF -DPYPOWSYBL_JAVA_LIBRARY_DIR=$GITHUB_WORKSPACE/dist/lib -DPYPOWSYBL_JAVA_INCLUDE_DIR=$GITHUB_WORKSPACE/dist/include
          cmake --build . --config Release

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: pypowsybl-wheel-${{ matrix.config.name }}-${{ matrix.python.name }}
          path: dist/*.whl
